AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch an EC2 instance with Apache in existing VPC"

Resources:
  # Instance definition
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-05943d624f2a7e87f" 
      InstanceType: "t2.micro" # Adjust as needed
      SecurityGroups: 
        - !Ref MySecurityGroup # Reference your existing security group ID
      SubnetId: !Ref MySubnet # Reference your existing subnet ID
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl start httpd
          systemctl enable httpd
          echo "Hello, world!" > /var/www/html/index.html

Outputs:
  PublicIp:
    Value: !GetAtt MyInstance.PublicIpAddress
